### ISSUE TITLE
does not work with Redmine 3.0.1

### ISSUE THREAD

**Issue by topkool** [hdgarrood/redmine_release_notes#120]
With a fresh Redmine 3.0.1 install, the plugin does not work when installing the plugin ("can't redefine the primary key column Id")

**Comment by mhiemstrapodiumtv** [comment]
I am having this same issue. Please fix!

**Comment by jniltinho** [comment]
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

you can't redefine the primary key column 'id'. To define a custom primary key, pass { id: false } to redmine/plugins/redmine_release_notes/db/migrate/001_create_release_notes.rb:20:in `block in up'
redmine/plugins/redmine_release_notes/db/migrate/001_create_release_notes.rb:19:in `up'

[code]
class CreateReleaseNotes < ActiveRecord::Migration
  def up
    create_table :release_notes do |t|
      #t.column :id, :integer
      t.column :issue_id, :integer
      t.column :text, :string
    end
  end

  def down
    drop_table :release_notes
  end
end

[/code]
