### ISSUE TITLE
Rake command fails

### ISSUE THREAD

**Issue by mhiemstrapodiumtv** [hdgarrood/redmine_release_notes#122]
Hi,

I am trying to install the release notes plugin for redmine. When executing the rake command I see this on my screen.

```
/usr/share/redmine/lib/plugins/redmine_release_notes$ sudo rake redmine:plugins:migrate RAILS_ENV=production --trace
(in /usr/share/redmine)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
Missing helper file helpers/release_notes_helper.rb
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:317:in `rescue in depend_on'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:312:in `depend_on'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:225:in `require_dependency'
/usr/lib/ruby/vendor_ruby/abstract_controller/helpers.rb:135:in `block in modules_for_helpers'
/usr/lib/ruby/vendor_ruby/abstract_controller/helpers.rb:131:in `map!'
/usr/lib/ruby/vendor_ruby/abstract_controller/helpers.rb:131:in `modules_for_helpers'
/usr/lib/ruby/vendor_ruby/action_controller/metal/helpers.rb:92:in `modules_for_helpers'
/usr/lib/ruby/vendor_ruby/abstract_controller/helpers.rb:95:in `helper'
/usr/share/redmine/lib/plugins/redmine_release_notes/lib/redmine_release_notes/issues_controller_patch.rb:21:in `block in perform'
/usr/share/redmine/lib/plugins/redmine_release_notes/lib/redmine_release_notes/issues_controller_patch.rb:20:in `class_eval'
/usr/share/redmine/lib/plugins/redmine_release_notes/lib/redmine_release_notes/issues_controller_patch.rb:20:in `perform'
/usr/share/redmine/lib/plugins/redmine_release_notes/init.rb:25:in `block (3 levels) in <top (required)>'
/usr/share/redmine/lib/plugins/redmine_release_notes/init.rb:23:in `each'
/usr/share/redmine/lib/plugins/redmine_release_notes/init.rb:23:in `block (2 levels) in <top (required)>'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:429:in `_run__1849565999418415124__prepare__3052232046468045691__callbacks'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:405:in `__run_callback'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:81:in `run_callbacks'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/reloader.rb:74:in `prepare!'
/usr/lib/ruby/vendor_ruby/action_dispatch/middleware/reloader.rb:48:in `prepare!'
/usr/lib/ruby/vendor_ruby/rails/application/finisher.rb:47:in `block in <module:Finisher>'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `instance_exec'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `run'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in `each'
/usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in `run_initializers'
/usr/lib/ruby/vendor_ruby/rails/application.rb:136:in `initialize!'
/usr/lib/ruby/vendor_ruby/rails/railtie/configurable.rb:30:in `method_missing'
/usr/share/redmine/config/environment.rb:14:in `<top (required)>'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:251:in `block in require'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:236:in `load_dependency'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:251:in `require'
/usr/lib/ruby/vendor_ruby/rails/application.rb:103:in `require_environment!'
/usr/lib/ruby/vendor_ruby/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
/usr/lib/ruby/vendor_ruby/rake/task.rb:246:in `call'
/usr/lib/ruby/vendor_ruby/rake/task.rb:246:in `block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:241:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:241:in `execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:184:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:177:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:205:in `block in invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:203:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:203:in `invoke_prerequisites'
/usr/lib/ruby/vendor_ruby/rake/task.rb:183:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:177:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:170:in `invoke'
/usr/lib/ruby/vendor_ruby/rake/application.rb:143:in `invoke_task'
/usr/lib/ruby/vendor_ruby/rake/application.rb:101:in `block (2 levels) in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:101:in `each'
/usr/lib/ruby/vendor_ruby/rake/application.rb:101:in `block in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:110:in `run_with_threads'
/usr/lib/ruby/vendor_ruby/rake/application.rb:95:in `top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:73:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:160:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:70:in `run'
/usr/bin/rake:27:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
```

Anybody got a clue?

**Comment by DarkSideGeek** [comment]
I had that problem when I downloaded as Zip and unarchived as "redmine_release_notes_master". Must change name to just "redmine_release_notes". Based on your prompt, this is not your issue, but I thought I'd throw it out for anyone else who ran into it...

Next comment: I use RVM. Not sure if you do? But if so, my understanding is you can never run RVM/rails as 'sudo' because it discards the environment variables necessary to operate. At best, should be run w/o sudo using the UID of the installed app. At worst, you can use 'rvmsudo' which tries to preserve env-vars such as RAILS_ENV. Hope this is your issue.
