### ISSUE TITLE
configure formats error

### ISSUE THREAD

**Issue by mmiat** [hdgarrood/redmine_release_notes#127]
if I try to modify a format, I've Internal Error
in log I've:

> ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
  plugins/redmine_release_notes/app/controllers/release_notes_formats_controller.rb:41:in `update'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by mmiat** [comment]
with this change it seems ok
https://github.com/hdgarrood/redmine_release_notes/commit/da3d185f97e465a2d33717ea9b4e5ca977ed9b35
I think that it could be useful to create a new release and specify that now it works with redmine 3.x
